---
title: "What is RASA?"
description: |
  Open Source AI
author:
  - name: Danny Moon
  
date: 05-19-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction to RASA

For my senior project, I built a chatbot for the Data Science program at BYU-Idaho. If you look at big companies like IBM, Facebook, Google, Microsoft or Amazon all are working extensively on it and each building their own framework. I came across to RASA from my faculty mentor and I started to build a chatbot with RASA.

Now lets first understand what is RASA and what all it provides.
RASA stack is an open-source AI tool and being an opensource framework, It is easy to customize. 

Rasa comes up with 2 components —

**Rasa NLU** — a library for natural language understanding (NLU) which does the classification of intent and extract the entity from the user input and helps a chatbot to understand what the user is saying.

**Rasa Core** — a chatbot framework with machine learning-based dialogue management which takes the structured input from the NLU and predicts the next best action using a probabilistic model like LSTM neural network.
NLU and Core are independent and one can use NLU without Core, and vice versa. Though Rasa recommends using both.

**Here is the flow of Rasa**
Before we further discuss, Let me explain a few keywords.

**Intent** — Intent is nothing but what the user is aiming for. For example — if the user says “Reserve a time to talk to my professor tomorrow” the intent can be classified as to book a meeting.

**Entity** — Entity is to extract the useful information from the user input. From the example above “Reserve a time to talk with my professor tomorrow” the entities extracted would be whom and time. Whom — professor and Time — tomorrow.

**Stories** — Stories define the sample interaction between the user and the chatbot in terms of intent and action taken by the bot. Like in the example above, bot got the intent of reserve a meeting and entities like whom and time but still, there is an entity missing — no of people and that would make the next action from the bot.

**Actions** — Actions are basically the operations performed by the bot either asking for some more details to get all the entities or integrating with some APIs or querying the database to get/save some information.

Now as we know some basics, Let’s dive into some actual actions. In this post, we will majorly focus on the Rasa Natural Language Understanding (NLU) which comprises of Intent Classification & Entity extraction and create a structured output which can be fed into Rasa Core.

**Rasa Natural Language Understanding (NLU)**

As we already briefed on NLU above, we need to teach our bot to understand our messages first. For that, we have to train the NLU model with our inputs in a simple text format and extract structured data. We will achieve this by defining the intents and providing a few ways users might express them.
To make this work, we need to define some files. Lets first understand these files.

**NLU training file**: It contains some training data in terms of user inputs along with the mapping of intents and entities present in each of them. The more varying examples you provide, better your bot’s NLU capabilities become.

**Stories file**: This file contains sample interactions the user and bot will have. Rasa (Core) creates a probable model of interaction from each story.

**Domain file**: This file lists all the intents, entities, actions, templates and some more information. The templates which I just mentioned is nothing but the sample bot reply which can be used as actions.

### My Thoughts on RASA

Here was my brief explanation on **Rasa**. I've never built a chatbot and Rasa was my first experience on chatbot. It had great documentation and Youtube tutorials to follow. Even if it was great, I can say that it's really hard to make a good chatbot that could answer the all of the questions that users will be asking. You have to put in all of use cases in the training data. It's very hard to come up with all the use cases. There is a better product called **Rasa X** and for me, it was pain and couldn't make it work. Even if I wasn't able to make **Rasa X** to work, but it is conversation driven AI and has much better feafure than **Rasa open source**. 